services:
    salvocortesiano.editorplus.listener:
        class: salvocortesiano\editorplus\event\main_listener
        arguments:
            - '@config'
            - '@config_text'
            - '@dbal.conn'
            - '@ext.manager'
            - '@language'
            - '@template'
            - '@user'
            - '@controller.helper'
            - '%core.root_path%'
            - '@service_container'
        tags:
            - { name: event.listener }

    salvocortesiano.editorplus.acp_controller:
        class: salvocortesiano\editorplus\controller\acp_controller
        arguments:
            - '@cache.driver'
            - '@config'
            - '@config_text'
            - '@dbal.conn'
            - '@ext.manager'
            - '@language'
            - '@log'
            - '@request'
            - '@template'
            - '@user'

    salvocortesiano.editorplus.render_controller:
        class: salvocortesiano\editorplus\controller\render_controller
        arguments:
            - '@auth'
            - '@config'
            - '@request'
            - '@user'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '@dbal.conn'

    salvocortesiano.editorplus.prefs_controller:
        class: salvocortesiano\editorplus\controller\prefs_controller
        arguments:
            - '@dbal.conn'
            - '@request'
            - '@user'

    salvocortesiano.editorplus.draft_controller:
        class: salvocortesiano\editorplus\controller\draft_controller
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@request'
            - '@user'
            - '%core.table_prefix%'

    salvocortesiano.editorplus.checkup:
        class: salvocortesiano\editorplus\core\checkup
        arguments:
            - '@config'
            - '@config_text'
            - '@dbal.conn'
            - '@ext.manager'
            - '@language'
            - '@dbal.tools'
            - '@controller.helper'
            - '@service_container'
            - '%core.root_path%'
            - '%core.table_prefix%'

    salvocortesiano.editorplus.images:
        class: salvocortesiano\editorplus\core\images
        arguments:
            - '@config'
            - '@config_text'
            - '@dbal.conn'
            - '@controller.helper'
            - '%core.root_path%'
            - '%core.table_prefix%'

    salvocortesiano.editorplus.image_controller:
        class: salvocortesiano\editorplus\controller\image_controller
        arguments:
            - '@config'
            - '@language'
            - '@request'
            - '@user'
            - '@salvocortesiano.editorplus.images'

    salvocortesiano.editorplus.acp_images_controller:
        class: salvocortesiano\editorplus\controller\acp_images_controller
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@ext.manager'
            - '@language'
            - '@log'
            - '@pagination'
            - '@request'
            - '@template'
            - '@user'
            - '@salvocortesiano.editorplus.images'
            - '%core.root_path%'
            - '%core.php_ext%'

    salvocortesiano.editorplus.katex_updater:
        class: salvocortesiano\editorplus\core\katex_updater
        arguments:
            - '@config'
            - '%core.root_path%'

    salvocortesiano.editorplus.cron.task.cleanup:
        class: salvocortesiano\editorplus\cron\task\cleanup
        arguments:
            - '@config'
            - '@dbal.conn'
            - '@attachment.manager'
            - '@log'
            - '%core.table_prefix%'
        calls:
            - [set_name, [cron.task.salvocortesiano.editorplus.cleanup]]
        tags:
            - { name: cron.task }
